const categoriesMockList = [
  { id: '1', name: 'Xi Măng', parentId: null },
  { id: '2', name: 'Thép', parentId: null },
  { id: '3', name: 'Gạch', parentId: null },
  { id: '4', name: 'Cát', parentId: null },
  { id: '5', name: 'Đá', parentId: null },
  { id: '6', name: 'Sơn', parentId: null },
  { id: '7', name: 'Cửa Kính', parentId: null },
  { id: '8', name: 'Nội Thất', parentId: null },
  { id: '9', name: 'Đèn Trang Trí', parentId: null },
  { id: '10', name: 'Vật Liệu Chịu Nhiệt', parentId: null },
  { id: '11', name: 'Thiết Bị Vệ Sinh', parentId: null },
  { id: '12', name: 'Thiết Bị Điện', parentId: null },
  { id: '13', name: 'Cây Cảnh', parentId: null },
  { id: '14', name: 'Vật Liệu Lót Sàn', parentId: null },
  { id: '15', name: 'Thạch Cao', parentId: null },
];

const brandsMockList = [
  { id: '1', name: 'Insee' },
  { id: '2', name: 'Holcim' },
  { id: '3', name: 'Lafarge' },
  { id: '4', name: 'Sika' },
  { id: '5', name: 'BASF' },
  { id: '6', name: 'Saint-Gobain' },
  { id: '7', name: 'Cemex' },
  { id: '8', name: 'Boral' },
  { id: '9', name: 'HeidelbergCement' },
  { id: '10', name: 'Mapei' },
  { id: '11', name: 'Knauf' },
  { id: '12', name: 'USG Boral' },
  { id: '13', name: 'Armstrong' },
  { id: '14', name: 'Fosroc' },
  { id: '15', name: 'Wacker Chemie' },
  { id: '16', name: 'Grace Construction Products' },
  { id: '17', name: 'James Hardie' },
  { id: '18', name: 'Kingspan' },
  { id: '19', name: 'Xella' },
  { id: '20', name: 'GCP Applied Technologies' },
  { id: '21', name: 'Etex' },
  { id: '22', name: 'Rockwool' },
  { id: '23', name: 'Dow' },
  { id: '24', name: 'DuPont' },
  { id: '25', name: 'Johns Manville' },
  { id: '26', name: 'Knauf Insulation' },
  { id: '27', name: 'Owens Corning' },
  { id: '28', name: 'PPG Industries' },
  { id: '29', name: 'Sherwin-Williams' },
  { id: '30', name: 'Nippon Paint' },
];

const FakeData = {
  categoriesMockList,
  brandsMockList,
};

module.exports = FakeData;
